# Generated by Django 2.1.7 on 2019-12-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='what',
            field=models.CharField(default=200, max_length=200),
            preserve_default=False,
        ),
    ]
